version: '3'
services:
  dev:
    image: node:12
    volumes:
        - .:/usr/src/service
    working_dir: /usr/src/service
    command: node server
    ports:
        - 3001:3001
    container_name: recipe_server
    tty: true