version: '2'
services:
  base:
    image: node:12
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service

  install:
    extends:
      service: base
    command: bash -c "npm i && npm install -g sass && npm run build"
  build:
    extends:
      service: base
    command: npm run build
  create-bundles:
    extends:
      service: base
    command: npm run create-bundles
  create-app:
    extends:
      service: base
    command: npx create-react-app recipe